#!/usr/bin/env python3
"""Build the browser-readable fallback for Lifeline's sealed synthetic demo."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEMO = ROOT / "web" / "demo"
TARGET = ROOT / "web" / "demo-data.js"


def read_json(name: str) -> dict:
    return json.loads((DEMO / name).read_text(encoding="utf-8"))


def main() -> None:
    payload = {
        "room": read_json("room.geojson"),
        "plan": read_json("plan.json"),
        "seal": read_json("plan.seal.json"),
        "verification": read_json("verification.json"),
        "verificationSeal": read_json("verification.seal.json"),
        "simulation": read_json("simulation.json"),
    }
    agent = DEMO / "agent_briefing.json"
    agent_seal = DEMO / "agent_briefing.seal.json"
    if agent.exists() and agent_seal.exists():
        payload["agent"] = read_json("agent_briefing.json")
        payload["agentSeal"] = read_json("agent_briefing.seal.json")
    encoded = json.dumps(payload, ensure_ascii=False, separators=(",", ":"), sort_keys=True)
    TARGET.write_text(
        "/* Generated by tools/build_demo_bundle.py from web/demo/. Do not edit by hand. */\n"
        f"window.LIFELINE_BUNDLED_DEMO={encoded};\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
